### ISSUE TITLE
Support for metal atoms

### ISSUE THREAD

**Issue by frgoe003** [forlilab/Meeko#252]
I'm using the cli to prepare metalloproteins for docking, however, it seems to have issues with some metals:

`RuntimeError: Element Na doesn't have an implemented covalent radius, which was required for the perception of intermolecular bonds` I encounter this error for a couple elements like Na, Co, Ni, Pt, Yb and K.

It seems meeko uses the [rdkit periodic table module](https://www.rdkit.org/docs/source/rdkit.Chem.PeriodicTable.html) to get the radii. Is there a way to bypass it or use a dummy value? Or maybe it could be added to be considered under the `--allow_bad_res` flag.

**Comment by rwxayheee** [comment]
Hi @frgoe003 
At present, the supported types of elements are very limited. They only have a defined covalent radius if they have an AutoDock atom type for receptor preparation. 
The covalent radii were put in as a dictionary (not from the periodic table module) so it’s always possible to allow more elements, but the same time we will need to register the atom type. Overall it’s technically possible to bypass it. 

Currently unsupported elements can’t be automatically ignored by -a. But you could delete them by argument delete_residues.

**Comment by frgoe003** [comment]
Understood, thanks! What would be required to register an atom type? Since quite common metals are missing, it would be nice to add them. Happy to help!

**Comment by rwxayheee** [comment]
Hi @frgoe003 
To bypass the element check, you could start from 
https://github.com/forlilab/Meeko/blob/07a38f8bac4aa9eef4ef30aa8e67475b15d517aa/meeko/utils/rdkitutils.py#L254

Then if you want to do receptor preparation, I think the additional elements need to be registered in here also
https://github.com/forlilab/Meeko/blob/07a38f8bac4aa9eef4ef30aa8e67475b15d517aa/meeko/data/params/ad4_types.json

There might be other things to edit if you want to do this by changing the default parameter file (or alternatively in Python, there's an entry to input additional parameters). But unlike ligand preparation, it's not very straightforward to have metals and custom types in receptor preparation. 

Could you provide some PDB IDs that you would be interested in (for receptor preparation)? There might be other complications if the metals are part of a residue and need monomer mapping. But please keep this discussion open and we can consider it as an enhancement / feature in future

Last but not least, if you only want a PDBQT file with the metal ions, the quickest way would be to insert the metal atom line directly and assign an integer charge. Then depending on the docking engines or next tasks you want to perform on the structure, you can pass the additional parameters in different ways (it might not be necessary to register the parameters and types in Meeko, although with the parameters

**Comment by frgoe003** [comment]
Thanks @rwxayheee! An example system I'm looking at is [8J3C](https://www.rcsb.org/structure/8J3C). 

I added the covalent radii in [Meeko/meeko/utils/rdkitutils.py](https://github.com/forlilab/Meeko/blob/07a38f8bac4aa9eef4ef30aa8e67475b15d517aa/meeko/utils/rdkitutils.py) and registered them in [Meeko/meeko/data/params/ad4_types.json](https://github.com/forlilab/Meeko/blob/07a38f8bac4aa9eef4ef30aa8e67475b15d517aa/meeko/data/params/ad4_types.json), but now it fails to build the template (see below).

I would add the metal ion directly to the PDBQT File, but receptor preparation raises an error with these metals present. Of course I could remove them before the preparation, but it would be nice to have native support with Meeko.

<details>
  <summary>Input residues {'-:1': 'CO'} not in residue_templates</summary>

```
  Input residues {'-:1': 'CO'} not in residue_templates
  
  Trying to resolve unknown residues by building chemical templates... 
  Failed building template from CCD for resname='CO'
  
  Error: Creation of data structure for receptor failed.
  
  Column name not found: _chem_comp_bond.atom_id_1
  Traceback (most recent call last):
  
    File "/home/user/miniconda3/envs/docking/lib/python3.11/site-packages/meeko/polymer.py", line 853, in __init__
      cc = build_noncovalent_CC(resname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/user/miniconda3/envs/docking/lib/python3.11/site-packages/meeko/chemtempgen.py", line 619, in build_noncovalent_CC
      cc_from_cif = ChemicalComponent.from_cif(fetch_from_pdb(basename), basename)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/user/miniconda3/envs/docking/lib/python3.11/site-packages/meeko/chemtempgen.py", line 398, in from_cif
      bond_cols = {attr: bond_table.find_column(f"{bond_category}{attr}") for attr in bond_attributes}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/user/miniconda3/envs/docking/lib/python3.11/site-packages/meeko/chemtempgen.py", line 398, in <dictcomp>
      bond_cols = {attr: bond_table.find_column(f"{bond_category}{attr}") for attr in bond_attributes}
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  RuntimeError: Column name not found: _chem_comp_bond.atom_id_1

```

**Comment by rwxayheee** [comment]
Hi @frgoe003 
Thanks for reporting this. It seems like the template generation function was trying to get the chemical template for Co2+ ion from the Protein Data Bank. We should skip the template making part for single-atom molecule. 
Sorry for the late response, and thanks for the example. I will work on it this week.

**Comment by rwxayheee** [comment]
Hello @frgoe003 
There're only very small changes I did in the code to allow Co2+ (and other metal ions in receptor with a provided covalent radius & ad4 atom type). These ions will still be fetched from PDB, but the missing bond section is forgiven. 

If you're interested, see how that compares to the release: 
https://github.com/forlilab/Meeko/compare/release...rwxayheee:Meeko:metal_support

With this, I was able to generate receptor PDBQT files for [8J3C](https://www.rcsb.org/structure/8J3C). Co2+ has an integer charge of +2. 

To use the modified code, you can check out that specific commit 32a7b3d from my fork and install with `pip install .`. In the near future I will create a PR with it. Thanks again for bringing this to our attention.

**Comment by ullibodnar** [comment]
Hello! Sorry to open this back up. I'm looking to perform receptor preparation with PDB [2Y9X](https://www.rcsb.org/structure/2Y9X). However, this protein (tyrosinase) has two copper cofactors in the binding site throwing a similar error to what @frgoe003 was seeing. In my case, it is `RuntimeError: Element Cu doesn't have an implemented covalent radius, which was required for the perception of intermolecular bonds.` Is it possible to add the covalent radius (1.32) and register the atom type as done with the other metal ions?

**Comment by diogomart** [comment]
@ullibodnar copper added in https://github.com/forlilab/Meeko/pull/462

**Comment by ullibodnar** [comment]
Please excuse my ignorance, but should we also add the covalent radius in rdkutils.py?

**Comment by diogomart** [comment]
@ullibodnar you are looking at an older version. Commit https://github.com/forlilab/Meeko/commit/6cc81af85e98621cc79697508e760de24ba61bac removed the covalent radius from `rdkitutils.py`, uses `covalent_radius_table.py` instead, which includes copper.

**Comment by ullibodnar** [comment]
Hi @diogomart, my mistake! Thanks again for that fix! 

After updating to the latest develop branch (with copper included via covalent_radius_table.py), the original covalent-radius error is resolved. However, I’m still running into template matching issues when preparing PDB 2Y9X with mk_prepare_receptor.py.

Specifically, the residues coordinating the dicopper active site (CuA/CuB and their six coordinating histidines: His61, His85, His94, His259, His263, His296) are reported as having “excess inter-residue bond(s)”, and when using --allow_bad_res they are removed from the prepared receptor entirely.

Since these histidines coordinate the catalytic copper ions, removing them effectively deletes the active site geometry required for docking validation (e.g., redocking tropolone, the inhibitor present in the crystal structure).

My understanding is that this may not be a missing-radius issue anymore, but rather that the Cu–His coordination bonds fall outside the default residue templates expected by the polymer builder.

Would the recommended approach here be:
	1.	defining custom residue templates for Cu-coordinated histidines using --add_templates, or
	2.	modifying the Cu template itself to allow coordination links, or
	3.	is there already a supported way to handle metalloprotein coordination environments like tyrosinase’s dicopper site during receptor preparation?

Just trying to determine whether this is something I should address with custom templates locally, or whether metalloprotein coordination like this is planned to be handled more directly in Meeko.

**Comment by diogomart** [comment]
Fixed in https://github.com/forlilab/Meeko/pull/463, but there's another problem: a covalent bond between Cys 83 and His 85. Seems like this is real, e.g.: https://www.tandfonline.com/doi/full/10.1080/09168451.2019.1696178#abstract

Not sure Meeko can handle this with the current template system. I can't work on it right now, but me or someone will get back to this eventually.

<img width="640" height="514" alt="Image" src="https://github.com/user-attachments/assets/d96f893b-ddbb-42d0-a5ed-5a60218965ee" />

**Comment by diogomart** [comment]
A possibly reasonable temporary solution would be to mutate the Cys to Ala

**Comment by ullibodnar** [comment]
Thank you for your assistance with this; it's greatly appreciated. For now, I am using the base prepare_receptor from the ADFR suite, and it seems to be working OK.
