### ISSUE TITLE
AssertionError when transfer mol2 file to pdbqt file

### ISSUE THREAD

**Issue by songyingit** [forlilab/Meeko#34]
Hi,

Recently when I tried to transfer mol2 file to pdbqt file, I met with this error. Could you please help me about this? It seems that meeko could not get the SMILES from the structure. (The structure has a ring inside)

Thanks in advance.

```
Traceback (most recent call last):
  File "/home/song/anaconda3/envs/my-rdkit-env/bin/mk_prepare_ligand.py", line 292, in <module>
    pdbqt_string = preparator.write_pdbqt_string()
  File "/home/song/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/meeko/preparation.py", line 198, in write_pdbqt_string
    return self._writer.write_string(self.setup, add_index_map, remove_smiles)
  File "/home/song/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/meeko/writer.py", line 144, in write_string
    smiles, order = self.setup.get_smiles_and_order()
  File "/home/song/anaconda3/envs/my-rdkit-env/lib/python3.9/site-packages/meeko/molsetup.py", line 572, in get_smiles_and_order
    assert(len(parents) == 1)
AssertionError
```

**Comment by diogomart** [comment]
Hi,

Thanks for reporting. Can you share the mol2 file that triggered this error?

**Comment by diogomart** [comment]
Closing, feel free to re-open or open a new issue
