### ISSUE TITLE
Bug while using --verbose

### ISSUE THREAD

**Issue by althea-hansel** [forlilab/Meeko#61]
```
(reactive_prep) [ahansel@nodea0114 ca_scaffold1]$ mk_prepare_ligand.py -i reacted_carboxylic_acids_scaffold1.sdf --multimol_outdir . --reactive_smarts "O=CN(N)c" --reactive_smarts_idx 2 -v
Traceback (most recent call last):
  File "/gpfs/home/ahansel/miniconda3/envs/reactive_prep/bin/mk_prepare_ligand.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/gpfs/home/ahansel/programs/Meeko/scripts/mk_prepare_ligand.py", line 366, in <module>
    if args.verbose: preparator.show_setup()
AttributeError: 'MoleculePreparation' object has no attribute 'show_setup'
```

**Comment by althea-hansel** [comment]
Fixed with commit [f868873](https://github.com/forlilab/Meeko/commit/f868873786f9fb96b2860732312152edd591a2d5)
