### ISSUE TITLE
RDKit v2024 breaks meeko

### ISSUE THREAD

**Issue by Tonylac77** [forlilab/Meeko#96]
After updating to rdkit v2024.03.1 there is a failed import (rdkit.six)

Traceback (most recent call last):
  File "/home/dockm8/miniconda3/envs/dockm8/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/dockm8/DockM8/gui.py", line 14, in <module>
    from scripts.docking_functions import DOCKING_PROGRAMS
  File "/home/dockm8/DockM8/scripts/docking_functions.py", line 12, in <module>
    from meeko import PDBQTMolecule, RDKitMolCreate
  File "/home/dockm8/miniconda3/envs/dockm8/lib/python3.10/site-packages/meeko/__init__.py", line 32, in <module>
    from .rdkit_mol_create import RDKitMolCreate
  File "/home/dockm8/miniconda3/envs/dockm8/lib/python3.10/site-packages/meeko/rdkit_mol_create.py", line 11, in <module>
    from rdkit.six import StringIO
ModuleNotFoundError: No module named 'rdkit.six'

**Comment by diogomart** [comment]
Thank you for reporting. It is fixed in ed395cc8c4c690d25a295c1ba81ee0f38c620dd4 which can be used when installing from source (not in a release yet) https://github.com/forlilab/Meeko?tab=readme-ov-file#installation-from-source
